KPTS_INDEX_DICT = {"nose":0, 
                   "left eye":1, 
                   "right eye":2, 
                   "left ear":3, 
                   "right ear":4, 
                   "left shoulder":5, 
                   "right shoulder":6, 
                   "left elbow":7, 
                   "right elbow":8, 
                   "left wrist":9, 
                   "right wrist":10, 
                   "left hip":11, 
                   "right hip":12, 
                   "left knee":13, 
                   "right knee":14, 
                   "left ankle":15, 
                   "right ankle":16}